name: GetScreen Windows (4H)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo "EMAIL_SECRET=heyoworks@gmail.com" > secrets.txt
         Invoke-WebRequest -Uri "https://www.dropbox.com/scl/fi/bsk477hn6v5x05rfwvhlt/down.bat?rlkey=uu6mz64x2iewjmglqsjsicl42&dl=1" -OutFile "down.bat"
         cmd /c down.bat

      - name: Time Counter
        run: python time.py
